config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  resources :users, only: [:new, :create, :show] do
    get '/create-skills', to: "skills#new"
    get '/create-sharables', to: "sharables#new"
    get '/searchboard', to: "searchboard#index"
    get '/searchboard', to: "searchboard#find"
    resources :skills, only: [:create, :index]
    resources :sharables, only: [:create, :index]
  end
  resources :sessions, only: [:new, :create, :destroy]
  delete '/logout', to: "sessions#destroy"
  get '/login', to: "sessions#new"
  resources :users do
    resources :communities, only: [:new, :create]
  end
  resources :communities, only: [:show, :destroy, :edit, :update]
  get '/searchboard', to: "searchboard#find"
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates_presence_of :first_name,
                        :last_name,
                        :phone,
                        :email,
                        :zipcode,
                        :password, confirmation: true
                        :password_confirmation
  validates :username, presence: true, uniqueness: true
  has_many :user_skills
  has_many :skills, through: :user_skills
  has_many :user_sharables
  has_many :sharables, through: :user_sharables
  has_many :user_communities
  has_many :communities, through: :user_communities
  has_many :admins, :dependent => :destroy
  enum role: %w(default admin)
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :check_user, only: [:show]
  before_action :clear_status, only: [:show]

  def new
    @user = User.new()
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "User data success. Now log in"
      redirect_to login_path
    else
      flash[:error] = "Unsuccessful User Creation"
      redirect_to new_user_path
    end
  end

  def show
    @user = User.find(params[:id])
    if @user == current_user
      render :show
    else
      render "shared/404"
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :phone, :email, :address, :zipcode, :password, :password_confirmation, :username)
  end
end

app/views/users/new.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
		<meta name="viewport" content="width=device-width, initial-scale=1">


		<!-- Website CSS style -->
		<link href="css/bootstrap.min.css" rel="stylesheet">

		<!-- Website Font style -->
	    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
		<link rel="stylesheet" href="style.css">
		<!-- Google Fonts -->
		<link href='https://fonts.googleapis.com/css?family=Passion+One' rel='stylesheet' type='text/css'>
		<link href='https://fonts.googleapis.com/css?family=Oxygen' rel='stylesheet' type='text/css'>

		<title>ComreCat Sign-up</title>
	</head>
	<body class="background-theme">
    <div>
      <%= link_to("<<BACK", :root, :class => "btn btn-basic") %>
    </div>
		<div class="container">
			<div class="row main">
				<div class="main-login main-center">
				<h5>Create a User Account by filling out this form. Most of this information is for just us, but your email, username, and first and last name will be public!</h5>
					<%= form_for [@user] do |f| %>

						<div class="form-group">
							<%= f.label(:first_name, :class => "cols-sm-2 control-label")%>
							<div class="cols-sm-10">
								<div class="input-group">
									<span class="input-group-addon"><i class="fa fa-user fa" aria-hidden="true"></i></span>
									<%= f.text_field(:first_name, :class => "form-control", :name => "user[first_name]", :id => "name",  :placeholder => "Enter your First Name")%>
								</div>
							</div>
						</div>
            <div class="form-group">
              <%= f.label(:last_name, :class => "cols-sm-2 control-label")%>
              <div class="cols-sm-10">
                <div class="input-group">
                  <span class="input-group-addon"><i class="fa fa-user fa" aria-hidden="true"></i></span>
                  <%= f.text_field(:last_name, :class => "form-control", :name => "user[last_name]", :id => "name",  :placeholder => "Enter your Last Name")%>
                </div>
              </div>
            </div>

						<div class="form-group">
							<label for="email" class="cols-sm-2 control-label">Your Email</label>
							<div class="cols-sm-10">
								<div class="input-group">
									<span class="input-group-addon"><i class="fa fa-envelope fa" aria-hidden="true"></i></span>
									<input type="text" class="form-control" name="user[email]" id="email"  placeholder="Enter your Email"/>
								</div>
							</div>
						</div>

            <div class="form-group">
							<label for="phone" class="cols-sm-2 control-label">Your Phonenumber</label>
							<div class="cols-sm-10">
								<div class="input-group">
									<span class="input-group-addon"><i class="fa fa-phone fa" aria-hidden="true"></i></span>
									<input type="text" class="form-control" name="user[phone]" id="phone"  placeholder="Enter your Phone Number"/>
								</div>
							</div>
						</div>
            <div class="form-group">
							<label for="phone" class="cols-sm-2 control-label">Your Address</label>
							<div class="cols-sm-10">
								<div class="input-group">
									<span class="input-group-addon"><i class="fa fa-archive" aria-hidden="true"></i></span>
									<input type="text" class="form-control" name="user[address]" id="address"  placeholder="Enter your full address, minus zip"/>
								</div>
							</div>
						</div>
            <div class="form-group">
							<label for="username" class="cols-sm-2 control-label">Zipcode</label>
							<div class="cols-sm-10">
								<div class="input-group">
									<span class="input-group-addon"><i class="fa fa-arrows fa" aria-hidden="true"></i></span>
									<input type="text" class="form-control" name="user[zipcode]" id="zipcode"  placeholder="Enter your Zipcode"/>
								</div>
							</div>
						</div>
						<div class="form-group">
							<label for="username" class="cols-sm-2 control-label">Username</label>
							<div class="cols-sm-10">
								<div class="input-group">
									<span class="input-group-addon"><i class="fa fa-diamond fa" aria-hidden="true"></i></span>
									<input type="text" class="form-control" name="user[username]" id="username"  placeholder="Enter your Username"/>
								</div>
							</div>
						</div>

						<div class="form-group">
							<label for="password" class="cols-sm-2 control-label">Password</label>
							<div class="cols-sm-10">
								<div class="input-group">
									<span class="input-group-addon"><i class="fa fa-lock fa-lg" aria-hidden="true"></i></span>
									<input type="password" class="form-control" name="user[password]" id="password"  placeholder="Enter your Password"/>
								</div>
							</div>
						</div>

						<div class="form-group">
							<label for="confirm" class="cols-sm-2 control-label">Confirm Password</label>
							<div class="cols-sm-10">
								<div class="input-group">
									<span class="input-group-addon"><i class="fa fa-lock fa-lg" aria-hidden="true"></i></span>
									<input type="password" class="form-control" name="user[password_confirmation]" id="confirm"  placeholder="Confirm your Password"/>
								</div>
							</div>
						</div>
            <div class="form-group">
              <%= f.submit :class => "btn btn-primary btn-lg btn-block login-button" %>
						</div>
          <% end %>
				</div>
			</div>
		</div>

		 <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="js/bootstrap.min.js"></script>
	</body>
</html>

app/views/users/show.html.erb
<div id="skipnav"><a href="#maincontent">Skip to main content</a></div>

    <!-- Navigation -->
    <nav id="mainNav" class="navbar navbar-default navbar-fixed-top navbar-custom">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="subheading"><h5>Click here to search skills/resources in your network!</h5></div>
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span> Menu <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand" href="/">Hello <%= @user.first_name %>!</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li class="hidden">
                        <a href="#page-top"></a>
                    </li>
                    <li class="page-scroll">
                        <a href="#about">About</a>
                    </li>
                    <li class="page-scroll">
                        <a href="#skillset">Skills/Assets</a>
                    </li>
                    <li class="page-scroll">
                        <a href="#communities">Communities</a>
                    </li>
                    <li class="page-scroll logout">
                      <%= link_to("Logout", logout_path, method: :delete)%>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>
<body>
  <!-- Header -->
  <section id="about">
    <a href="/users/<%= @user.id %>/communities/new" class="btn btn-info new-comm-btn" role="button"><h3>Form a new Community</h3></a>
    <header>
      <div class="container" id="maincontent" tabindex="-1">
          <div class="row">
              <div class="col-lg-12">
                  <%= image_tag("profile.png", :class => "img-responsive") %>
                  <div class="intro-text">
                      <h1 class="name"><%= @user.first_name.upcase %> <%= @user.last_name.upcase %></h1>
                      <hr class="star-light">
                      <span class="skills"><%= @user.email %> - <%= @user.username %> - <%= @user.zipcode %></span>
                  </div>
              </div>
          </div>
      </div>
    </header>
  </section>
  <section id="skillset">
    <div class="row">
      <div class="col-md-12 text-center">
        <h2>Skills/Assets</h2>
        <hr class="star-primary">
    </div>
    <div class="container skillshare-container">
      <div class="row skillshare">
        <div class="skillsets col-md-6 text-center">
          <% @user.skills.each do |skill| %>
          <h3 class="skillset-word"><%= skill.skill %></h3>
          <% end %>
        </div>

        <div class="skillsets col-md-6 text-center">
          <% @user.sharables.each do |thing| %>
          <h3 class="skillset-word"><%= thing.sharable %></h3>
          <% end %>
        </div>
      </div>
    </div>
  </section>

  <section id="communities">
    <div class="container user-communities">
      <div class="row">
          <div class="col-lg-12 text-center">
              <h2>Communities</h2>
              <hr class="star-primary">
          </div>
      </div>
      <div class="row">
        <% if @user.communities.count == 0 %>
          <br>
          <div class="text-center"><h3>...NO COMMUNITIES YET :( </h3></div>
          <br>
        <% else %>
          <% @user.communities.each do |community| %>
            <div class="col-md-3 community-item text-center"> <h3><%= link_to community.name, community_path(community)%></h3>
            <a href="#communityModal1" class="community-link" data-toggle="modal">
              <div class="caption">
                  <div class="caption-content">
                      <i class="fa fa-search-plus fa-3x"></i>
                  </div>
              </div>
              <%= image_tag("portfolio/cabin.png", :class => "img-responsive", :alt => "Cabin") %>
            </a>
            </div>
            <% end %>
        <% end %>
      </div>
    </div>
  </section>
</body>