config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  resources :users, only: [:new, :create, :show] do
    get '/create-skills', to: "skills#new"
    get '/create-sharables', to: "sharables#new"
    get '/searchboard', to: "searchboard#index"
    get '/searchboard', to: "searchboard#find"
    resources :skills, only: [:create, :index]
    resources :sharables, only: [:create, :index]
  end
  resources :sessions, only: [:new, :create, :destroy]
  delete '/logout', to: "sessions#destroy"
  get '/login', to: "sessions#new"
  resources :users do
    resources :communities, only: [:new, :create]
  end
  resources :communities, only: [:show, :destroy, :edit, :update]
  get '/searchboard', to: "searchboard#find"
end

app/models/skill.rb
class Skill < ApplicationRecord
  has_many :user_skills
  has_many :users, through: :user_skills
  has_many :communities, through: :users
  validates :skill, presence: true
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  before_action :check_user, only: [:index]

  def new
    @user = User.find(params[:user_id])
    @skill = Skill.new()
  end

  def create
    @user = User.find(params[:user_id])
    @skill = Skill.new(skill_params)
    if @skill.save && @user.skills.count == 2
      @user.skills << @skill
      flash[:success] = "Alright that'll do for now. Well done. Continue adding if you'd like, but feel free to move on if you're ready. There'll be more chances to add skills later.."
      redirect_to user_skills_path(@user)
    elsif @skill.save
      @user.skills << @skill
      flash[:success] = "Fantastic! We didn't know you could do that! What else you got?"
      redirect_to user_skills_path(@user)
    else
      flash[:error] = "invalid skill... can't move on without listing at least three!"
      redirect_to user_create_skills_path(@user)
    end
  end

  def index
    @skill = Skill.new()
    @user = User.find(params[:user_id])
  end

  private

    def skill_params
      params.require(:skill).permit(:skill)
    end

end

app/views/skills/index.html.erb
<body class="background-theme">
<div>
  <%= link_to "<<Back to User info", edit_user_path(@user) %>
</div>
<h1>Tell us what other skills you have...</h1>
<div class="added_skills">
<% @user.skills.each do |skill| %>
 <p><%= skill.skill %></p>
<% end %>
</div>
<%= form_for [@user, @skill] do |f| %>
  <%= f.label :skill, "What else?" %>
  <%= f.text_field :skill %>
  <%= f.submit "add a skill!" %>
<% end %>
<%= link_to "next", user_create_sharables_path(@user) %>
</body>

app/views/skills/new.html.erb
<body class="background-theme">
<%= render partial: "shared/errors", locals: { target: @skill } %>
<br/><br/>
<h1>Tell us what skills you have...</h1>

<%= form_for [@user, @skill] do |f| %>
  <%= f.label :skill, "What are you good at?" %>
  <%= f.text_field :skill %>
  <%= f.submit "add a skill!" %>
<% end %>
</body>